[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/tmux/plugins/catppuccin/tmux"]
    type = "archive"
    url = "https://github.com/catppuccin/tmux/archive/refs/tags/v2.1.3.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
