-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives
---@module 'hl'
-- #######################################################################################
-- AUTOGENERATED HYPR CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################
-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/
-- Please note not all available settings / options are set here.
-- For a full list, see the wiki
-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf
--###############
--## MONITORS ###
--###############
-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "DP-2",
	mode = "2560x1440@270",
	position = "1440x800",
	scale = 1,
	vrr = 2,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "2560x1440@60",
	position = "0x0",
	scale = 1,
	transform = 3,
})

--##################
--## MY PROGRAMS ###
--##################
-- See https://wiki.hyprland.org/Configuring/Keywords/
-- Set programs that you use
local terminal = "ghostty"
local fileManager = "thunar"
local menu = "rofi -show drun"
hl.env("XCURSOR_SIZE", 24)
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

--####################
--## LOOK AND FEEL ###
--####################
-- Refer to https://wiki.hyprland.org/Configuring/Variables/
-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 2,
		gaps_out = 5,
		border_size = 2,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		-- col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
		-- col.inactive_border = rgba(595959aa)
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = true,
		layout = "master",
		col = {
			active_border = { colors = { "rgb(CFB981)", "rgb(EDA249)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = false,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.9,
		-- drop_shadow = true
		-- shadow_range = 4
		-- shadow_render_power = 3
		-- col.shadow = rgba(1a1a1aee)
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 4,
			passes = 2,
			vibrancy = 0.1696,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
	animations = {
		enabled = false,
	},
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		-- pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
		preserve_split = true,
		-- You probably want this
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		mfact = 0.5,
		new_status = "slave",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		-- no_direct_scanout = false
		force_default_wallpaper = 0,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true,
		-- If true disables the random hyprland logo / anime girl background. :(
	},
})

hl.config({
	cursor = {
		inactive_timeout = 5,
	},
})
--############
--## INPUT ###
--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		follow_mouse = 1,
		sensitivity = -1,
		-- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = false,
		},
		scroll_factor = 1,
	},
})

hl.device({
	name = "fnatic-gear-fnatic-gear-streak60-keyboard",
	kb_layout = "us_qwertz",
	kb_options = "caps:escape",
})

hl.device({
	name = "moergo-go60-left-keyboard",
	kb_layout = "us_qwertz",
})

-- device{
--   name = razer-razer-blackwidow-tournament-edition-chroma
--   kb_layout = us_qwertz,de
--   kb_options = caps:escape
-- }

hl.device({
	name = "dualsense-wireless-controller-touchpad",
	sensitivity = 1,
})

hl.config({
	ecosystem = {
		no_update_news = true,
		no_donation_nag = true,
	},
})

--###################

--## KEYBINDINGSS ###

--###################

-- See https://wiki.hyprland.org/Configuring/Keywords/
local mainMod = "SUPER"
-- Sets "Windows" key as main modifier
-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("ghostty"))
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))
-- bind = $mainMod, F, togglefloating,
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + " .. "Space", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle
-- bind = $mainMod, J, togglesplit, # dwindle
-- Move focus with mainMod + arrow keys
hl.bind("CTRL" .. " + " .. "h", hl.dsp.focus({ direction = "l" }))
hl.bind("CTRL" .. " + " .. "l", hl.dsp.focus({ direction = "r" }))
hl.bind("CTRL" .. " + " .. "k", hl.dsp.focus({ direction = "u" }))
hl.bind("CTRL" .. " + " .. "j", hl.dsp.focus({ direction = "d" }))
hl.bind("CTRL + SHIFT" .. " + " .. "h", hl.dsp.window.move({ direction = "l" }))
hl.bind("CTRL + SHIFT" .. " + " .. "l", hl.dsp.window.move({ direction = "r" }))
hl.bind("CTRL + SHIFT" .. " + " .. "k", hl.dsp.window.move({ direction = "u" }))
hl.bind("CTRL + SHIFT" .. " + " .. "j", hl.dsp.window.move({ direction = "d" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Resize windows
local resizeUnit = 100
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.resize({ x = resizeUnit, y = 0, relative = true }))
hl.bind(mainMod .. " + ALT + left", hl.dsp.window.resize({ x = -resizeUnit, y = 0, relative = true }))
hl.bind(mainMod .. " + ALT + up", hl.dsp.window.resize({ x = 0, y = -resizeUnit, relative = true }))
hl.bind(mainMod .. " + ALT + down", hl.dsp.window.resize({ x = 0, y = resizeUnit, relative = true }))

-- Type text currently in paste
hl.bind("ALT" .. " + " .. "V", hl.dsp.exec_cmd('wtype "$(wl-paste)"'))

-- Screenshot a selection and copy text to clipboard
hl.bind("PRINT", hl.dsp.exec_cmd('grim -g "$(slurp)"-| tesseract--| wl-copy'))
hl.bind(mainMod .. " + " .. "s", hl.dsp.exec_cmd("hyprshot -m region"))

-- Clipboard history
hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("cliphist list| rofi -dmenu| cliphist decode| wl-copy"))

-- Reload Waybar configuration
hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("pkill -SIGUSR2 waybar"))

-- Media controls
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind(
	"XF86AudioPlay",
	hl.dsp.exec_cmd("curl -sf http://localhost:32500/player/playback/playPause || playerctl play-pause"),
	{ locked = true }
)
hl.bind(
	"XF86AudioNext",
	hl.dsp.exec_cmd("curl -sf http://localhost:32500/player/playback/skipNext || playerctl next"),
	{ locked = true }
)
hl.bind(
	"XF86AudioPrev",
	hl.dsp.exec_cmd("curl -sf http://localhost:32500/player/playback/skipPrevious || playerctl previous"),
	{ locked = true }
)

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################
-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

hl.workspace_rule({
	workspace = 1,
	-- name = "coding",
	-- rounding = false,
	decorate = false,
	gaps_in = 0,
	gaps_out = 0,
	-- border = false,
	monitor = "DP-1",
	persistent = true,
	default = true,
})

hl.workspace_rule({
	workspace = 2,
	monitor = "DP-1",
	persistent = true,
})

hl.workspace_rule({
	workspace = 3,
	decorate = false,
	gaps_in = 0,
	gaps_out = 0,
	monitor = "DP-1",
	persistent = true,
})

hl.workspace_rule({
	workspace = 4,
	monitor = "DP-1",
	persistent = true,
})

hl.workspace_rule({
	workspace = 5,
	monitor = "DP-1",
	persistent = true,
})

hl.workspace_rule({
	workspace = 6,
	monitor = "HDMI-A-1",
	persistent = true,
})

hl.workspace_rule({
	workspace = 7,
	monitor = "HDMI-A-1",
	persistent = true,
})

hl.workspace_rule({
	workspace = 8,
	monitor = "HDMI-A-1",
	persistent = true,
})

hl.workspace_rule({
	workspace = 9,
	monitor = "HDMI-A-1",
	persistent = true,
})

hl.workspace_rule({
	workspace = 10,
	monitor = "HDMI-A-1",
	persistent = true,
})

hl.window_rule({
	name = "audacious",
	match = {
		class = "audacious",
	},
	workspace = "7 silent",
})

hl.window_rule({
	name = "Plexamp",
	match = {
		class = "Plexamp",
	},
	workspace = "7 silent",
})

hl.window_rule({
	name = "Open menu",
	match = {
		class = "^(Open File|Select a File|Open Folder|Save As|Library|File Upload)(.*)$",
	},
	float = true,
})

-- flot misc

hl.window_rule({
	name = "volume",
	match = {
		class = "^(pavucontrol|org\\.pulseaudio\\.pavucontrol|nm-connection-editor|Zotero|nwg-look)$",
	},
	float = true,
})

hl.window_rule({
	name = "TeamSpeak",
	match = {
		class = "TeamSpeak 3",
	},
	float = true,
})

hl.window_rule({
	name = "firefox",
	match = {
		class = "firefox",
	},
	workspace = "2",
})

hl.window_rule({
	name = "Steam",
	match = {
		class = "^([Ss]team)$",
	},
	workspace = "3 silent",
})

hl.window_rule({
	name = "match_title_friends_",
	match = {
		title = "Friends List",
	},
	float = true,
})

hl.window_rule({
	name = "match_title_deadlock",
	match = {
		title = "Deadlock",
	},
	immediate = true,
})

hl.window_rule({
	name = "DEATH STRANDING 2",
	match = {
		title = "DEATH STRANDING 2:ON THE BEACH",
	},
	immediate = true,
})

hl.window_rule({
	name = "match_title__binding",
	match = {
		title = ".*Binding of Isaac.*",
	},
	immediate = true,
})

hl.window_rule({
	name = "Steam Big Picture Mode",
	match = {
		title = "Steam Big Picture Mode",
	},
	immediate = true,
})

hl.window_rule({
	name = "shapez2",
	match = {
		title = "shapez 2",
	},
	immediate = true,
})

hl.window_rule({
	name = "Hollow Knight",
	match = {
		title = "Hollow Knight",
	},
	immediate = true,
})

hl.window_rule({
	name = "Silksong",
	match = {
		title = "Hollow Knight Silksong",
	},
	immediate = true,
})

hl.window_rule({
	name = "ANIMAL WELL",
	match = {
		title = "ANIMAL WELL",
	},
	immediate = true,
})

hl.window_rule({
	name = "Celeste",
	match = {
		title = "Celeste",
	},
	immediate = true,
})

hl.window_rule({
	name = "Detroit",
	match = {
		title = "Detroit:Become Human",
	},
	immediate = true,
})

hl.window_rule({
	name = "Plex",
	match = {
		class = "Plex",
	},
	workspace = "5",
})

hl.window_rule({
	name = "mpv",
	match = {
		class = "mpv",
	},
	workspace = "4",
})

hl.window_rule({
	name = "suppress-maximize-events",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("waybar")
	hl.exec_cmd("dunst")
	hl.exec_cmd("hyprctl setcursor MyCursor 24")
end)
