splash = false

preload = /home/alex/Documents/Wallpaper/tree_abstract.jpg

wallpaper {
	monitor = DP-2
	path = /home/alex/Documents/Wallpaper/tree_abstract.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = /home/alex/Documents/Wallpaper/tree_abstract.jpg
	fit_mode = cover
}
