$background = rgb(090609)
$foreground = rgb(FAF6EF)
$color0 = rgb(090609)
$color1 = rgb(7BA6C3)
$color2 = rgb(FB9B0A)
$color3 = rgb(EDA249)
$color4 = rgb(CFB981)
$color5 = rgb(B6CBCE)
$color6 = rgb(F3E8D2)
$color7 = rgb(F0EBE0)
$color8 = rgb(A8A49C)
$color9 = rgb(7BA6C3)
$color10 = rgb(FB9B0A)
$color11 = rgb(EDA249)
$color12 = rgb(CFB981)
$color13 = rgb(B6CBCE)
$color14 = rgb(F3E8D2)
$color15 = rgb(F0EBE0)
